security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    role_hierarchy:
        ROLE_ADMIN: [ ROLE_ACCOUNTANT ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # The authenticator manager no longer has "anonymous" security.
            # anonymous: true
            lazy: true
            provider: app_user_provider
#            json_login:
#                check_path: app_login
#                username_path: username
#                password_path: password
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\MyFacebookAuthenticator
                entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_static_about # app_any_route
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 3600 # 1 hour in seconds
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # matches /admin/users/*
        - { path: '^/admin/product', roles: [ROLE_ACCOUNTANT] }
#        - { path: '^/admin/users', roles: ROLE_ADMIN }
#        - { path: '^/admin/category', roles: ROLE_ADMIN }

        # matches /admin/* except for anything matching the above rule
        - { path: '^/admin', roles: ROLE_ADMIN }

    # Symfony version 5.1: Authenticator-based security
    enable_authenticator_manager: true